#pragma once

enum EventType
{
    MOUSE_LEFT_DOWN,
    MOUSE_LEFT_UP,
    MOUSE_RIGHT_DOWN,
    MOUSE_RIGHT_UP,
    MOUSE_MIDDLE_DOWN,
    MOUSE_MIDDLE_UP,
    MOUSE_X_DOWN,
    MOUSE_X_UP,
    MOUSE_SCROLL_DOWN,
    MOUSE_SCROLL_UP,

    MOUSE_MOVE
};