#ifndef _WORKTYPEENUM_H_
#define _WORKTYPEENUM_H_

enum TaskType
{
    TASK_BEGIN = 0,

    TASK_PC_MANAGE,
    TASK_JARVIS_MANAGE,

    TASK_VOLUME_CHANGE,
    TASK_GET_FOLDER_CONTENT,
    TASK_RENAME_DIR_ENTRY,
    TASK_INPUT_EVENTS,

    TASK_END
};


#endif // _WORKTYPEENUM_H_